### ISSUE TITLE
Typo in repository description

### ISSUE THREAD

**Issue by nhedger** [unjs/cookie-es#18]
### Environment

n/a

### Reproduction

n/a

### Describe the bug

I've just found a typo in the repository's description.

```diff
- 🍪 Cookie Serializer and Desrializer 
+ 🍪 Cookie Serializer and Deserializer 
```

### Additional context

<img width="395" alt="Screenshot 2023-10-22 at 06 30 59" src="https://github.com/unjs/cookie-es/assets/649677/2aa01b19-8647-421b-a109-a171d56e5d00">

_No response_

**Comment by pi0** [comment]
Thanks for notice ❤️
